=== Aequivinius/xml/E2/ex/attachments/distilleries.dtd
<!ELEMENT distilleries (distillery)+>

<!ELEMENT distillery (address, stills, bottlings)>
<!ATTLIST distillery name CDATA #REQUIRED>

<!ELEMENT address (#PCDATA)>
<!ELEMENT stills (still)+>
<!--A distillery has at least one still, otherwise there wouldn't be much distilling.-->
<!ELEMENT bottlings (bottling)*>
<!--The different products from a distillery are called bottlings.-->

<!ELEMENT still EMPTY>
<!--A still is a structure in distillation takes place-->

<!ATTLIST still type (column | pot) #REQUIRED>
<!--A still can be of one of two types: column or pot-->
<!ATTLIST still name CDATA #IMPLIED>
<!--A still can have a name-->

<!ELEMENT bottling EMPTY>
<!ATTLIST bottling name CDATA #REQUIRED>
<!ATTLIST bottling age CDATA #IMPLIED>
<!--The minimum age for Single Malt from Scotland must be 3 years -->

<!ATTLIST bottling category CDATA #FIXED "Single Malt">
<!--We could also consider other things, but why would we...?-->

=== Aequivinius/xml/E2/sol/attachments/distilleries.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE distilleries SYSTEM "distilleries.dtd">

<distilleries>
    <distillery name="scapa">
        <address>Kirkwall KW15 1SE, UK</address>
        
        <stills>
            <still type="pot"/>
            <still type="pot"/>
        </stills>
        
        <bottlings>
            <bottling name="Scapa Skiren" age="" category="Single Malt"/>
        </bottlings>
    </distillery>
    
    <distillery name="mortlach">
        <address>2 Fife St, Dufftown, Keith AB55 4EH, UK
        </address>
        
        <stills>
            <still type="pot"/>
            <still type="pot"/>
            <still type="pot"/>
            <still type="pot"/>
            <still type="pot"/>
            <still type="pot" name="Wee Witchie"/>
        </stills>
        
        <bottlings>
            <bottling name="Mortlach 18" age="18" category="Single Malt"/>
        </bottlings>
    </distillery>
    
</distilleries>
